webtalk_init -webtalk_dir /home/sergio/gpio/gpio.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "lun dic 4 09:29:03 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211449201_0_0_267" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "n5ssk9abicfpvb3l9q7ggdc24f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3409.934 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1512373812000" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1512373812000"
webtalk_add_data -client sdk -key uid -value "1512373895000" -context "sdk\\\\bsp/1512373895000"
webtalk_add_data -client sdk -key hwid -value "1512373812000" -context "sdk\\\\bsp/1512373895000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1512373895000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1512373895000"
webtalk_add_data -client sdk -key uid -value "1512373896000" -context "sdk\\\\application/1512373896000"
webtalk_add_data -client sdk -key hwid -value "1512373812000" -context "sdk\\\\application/1512373896000"
webtalk_add_data -client sdk -key bspid -value "1512373895000" -context "sdk\\\\application/1512373896000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1512373896000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1512373896000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1512373896000"
webtalk_transmit -clientid 3838250368 -regid "211449201_0_0_267" -xml /home/sergio/gpio/gpio.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/sergio/gpio/gpio.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/sergio/gpio/gpio.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
